#!/bin/bash
# Write apps/openmw/vita/VitaBuildId.h with this build's identifier:
#   <git short hash>[+dirty]-<YYYYmmdd-HHMMSS>
# The game logs it at boot ("[Build] id=...") and archive-build.sh stores the
# linked ELF under the same id, so a crash log names the exact symbols that
# match it. Called by build.sh / build-fast.sh before make. Prints the id.
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
OUT="${SRC_DIR}/apps/openmw/vita/VitaBuildId.h"

HASH="$(git -C "${SRC_DIR}" rev-parse --short=10 HEAD 2>/dev/null || echo nogit)"
if [ -n "$(git -C "${SRC_DIR}" status --porcelain --untracked-files=no 2>/dev/null)" ]; then
    HASH="${HASH}+dirty"
fi
ID="${HASH}-$(date +%Y%m%d-%H%M%S)"

cat > "${OUT}" <<EOF
// Generated by scripts/vita/build-id.sh. Not tracked in git.
#define VITA_BUILD_ID "${ID}"
EOF
echo "${ID}"
