#!/bin/bash
# Regenerate apps/openmw/vita/VitaGLGuardList.h from the linked vitaGL.
#
# The GL guard (apps/openmw/vita/VitaGLGuard.cpp) wraps every listed
# function with an owner-thread check via `ld --wrap`. Only symbols vitaGL
# actually defines may be listed: each wrapper references __real_<fn>,
# which must resolve. Re-run after bumping VITAGL_COMMIT in
# scripts/vita-deps/build-vitagl.sh and commit the result.
#
# Usage: scripts/vita/gen-glguard-list.sh [path/to/libvitaGL.a]
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
VITASDK="${VITASDK:-/usr/local/vitasdk}"
LIB="${1:-${VITAGL_DIR:-${HOME}/vitaGL}/libvitaGL.a}"
OUT="${SRC_DIR}/apps/openmw/vita/VitaGLGuardList.h"

if [ ! -f "${LIB}" ]; then
    echo "ERROR: ${LIB} not found (build vitaGL first: scripts/vita-deps/build-vitagl.sh)"
    exit 1
fi

COMMIT="$(git -C "$(dirname "${LIB}")" rev-parse --short HEAD 2>/dev/null || echo unknown)"

# Every gl* entry point, plus vglSwapBuffers (GXM scene end + display queue).
SYMS="$("${VITASDK}/bin/arm-vita-eabi-nm" "${LIB}" \
    | awk '$2 == "T" && ($3 ~ /^gl[A-Z]/ || $3 == "vglSwapBuffers") { print $3 }' \
    | sort -u)"

{
    echo "// Generated by scripts/vita/gen-glguard-list.sh from vitaGL ${COMMIT}. Do not edit."
    echo "// One VGL_GUARD(fn) per vitaGL entry point wrapped by the GL guard."
    for s in ${SYMS}; do
        echo "VGL_GUARD(${s})"
    done
} > "${OUT}"

echo "Wrote $(echo "${SYMS}" | wc -l | tr -d ' ') entries to ${OUT}"
